### ISSUE TITLE
Funcube Dongle Pro+ with GQRX

### ISSUE THREAD

**Issue by ik8ozv** [dl1ksv/gr-funcube#10]
Please anybody can help me to get it working under GQRX?
When i try to select the I/O Device, i can see two devices, one named
FUNCube Dongle V2.0 and another one named FUNCube Dongle V2.0 Stereo Analogico.
the first one has as Device string FCD=0
while the second one has as Device default_input=True,default_output=False,device_id=0,driver=audio,soapy=0.
If i select the first one the program closes down while if i choose the second one i bet the audio distorted and mixed with the background noise. It is not clear.
Please any help?
Thanks
Enzo

**Comment by dl1ksv** [comment]
Which drivers are linked to gqrx? They are reported on startup. On my system I get
$gqrx
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio v3.11.0.0git-428-g131e733a
built-in source types: file fcd rtl rtl_tcp rfspace soapy redpitaya

Did you build gqrx from source ?

The device string FCD=0 is correct.

**Comment by ik8ozv** [comment]
I am not so clever on Linux.
Will you please tell how to check which drivers are linked to gqrx?

Fir the GQRX I just gave in terminal the command:

sudo apt-get install gqrx-sdr 

Thanks
 
 73’s de Enzo IK8OZV

**Comment by dl1ksv** [comment]
Just run the gqrx executable in a terminal window and have a look at the output.

**Comment by ik8ozv** [comment]
When i run gqrx in the Terminal Window i get:

gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.1.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
file_source :warning: file size is not a multiple of item size
Resampling audio 96000 -> 48000
BandPlanFile is /home/enzo/.config/gqrx/bandplan.csv
BookmarksFile is /home/enzo/.config/gqrx/bookmarks.csv
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
libusb: warning [libusb_exit] device 1.1 still referenced
libusb: warning [libusb_exit] device 2.5 still referenced
libusb: warning [libusb_exit] device 2.4 still referenced
libusb: warning [libusb_exit] device 2.3 still referenced
libusb: warning [libusb_exit] device 2.2 still referenced
libusb: warning [libusb_exit] device 2.1 still referenced

then i get the gqrx error window which says:

Gqrx has detected problems with the
current configuration.Loading the
application to crash.
Do you want to edit settings?

If i click on NO it continues with:

gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.1.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
Using FUNcube Dongle V2.0 (hw:1)
Errore di segmentazione (core dump creato)

but the gqrx seems does not load as i do not see it.

If i click on YES i get the GQRX ConfigureI/o devices window poping up.
I leace all at it is and click on OK and it does the same as above,
And also in this case, the gqrx seems does not load as i do not see it.
Thanks

73's de Enzo IK8OZV

**Comment by dl1ksv** [comment]
@Enzo in #11 you mentioned that you were able to decode a FM Radio station clearly in gnuradio.  
If so it's a problem of gqrx/ gr-osmosdr not  of  gr-funcube.

What happens if you try to edit the configuration? 
You should use FUNCube Dongle V2.0 and the fcd=0.
Make sure to select the correct inputrate  192000 and decimation none.
The libusb warnings look strange. I've never seen them before.
But I think you should ask on https://github.com/gqrx-sdr/gqrx/issues

**Comment by ik8ozv** [comment]
@dl1ksv yes correct but i have also noticed and forgot to say that if i try a satellite flowgraph that it is with gr-satellites i do not get any byte.
In the first message above i said:

When i try to select the I/O Device, i can see two devices, one named
FUNCube Dongle V2.0 and another one named FUNCube Dongle V2.0 Stereo Analogico.
the first one has as Device string:

FCD=0

while the second one has as Device string:

default_input=True,default_output=False,device_id=0,driver=audio,soapy=0.

If i select the first one the program closes down
while if i choose the second one i get the audio distorted and mixed with the background noise. It is not clear.
Thanks

73's de Enzo IK8OZV

**Comment by ik8ozv** [comment]
@dl1ksv 
If i run GQRX in the terminal window, i get:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.1.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
file_source :warning: file size is not a multiple of item size
Resampling audio 96000 -> 48000
BandPlanFile is /home/enzo/.config/gqrx/bandplan.csv
BookmarksFile is /home/enzo/.config/gqrx/bookmarks.csv
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
libusb: warning [libusb_exit] device 1.1 still referenced
libusb: warning [libusb_exit] device 2.5 still referenced
libusb: warning [libusb_exit] device 2.4 still referenced
libusb: warning [libusb_exit] device 2.3 still referenced
libusb: warning [libusb_exit] device 2.2 still referenced
libusb: warning [libusb_exit] device 2.1 still referenced

Thanks
73's de Enzo IK8OZV

**Comment by dl1ksv** [comment]
Did you try to edit the device settings? You must choose the device that has the device string fcd=0.
I think, the second entry references a soapy driver that has it's own fcd driver implementation.
I just built gqrx from scratch together with gr-funcube and I get only one device for the dongle and this works.

**Comment by ik8ozv** [comment]
yes i did but i get the error shown here:

https://ibb.co/9ZQH8Q6

Thanks

**Comment by dl1ksv** [comment]
You install gqrx from the repository of your linux distro. But what distro are you using? Ubuntu, Debian, Fedora ...?
You have to start gqrx in a terminal window to get more error messages.

It's strange that you see the Funcube Dongle twice.

You can try to download the official [release](https://github.com/gqrx-sdr/gqrx/releases/download/v2.16/Gqrx-2.16-x86_64.AppImage).
Don't forget to make the downloaded file executable ( chmod +x <filename>) 

I tested this executable and it works for me though it reports the libusb warnings you have seen.

**Comment by ik8ozv** [comment]
@dl1ksv 
Please Apologies if I forgot to
Mention the distro I am using.
It is UBUNTU 23.04
I am not to familiar with Linux so I ask you please if you can tell me how to unistall the actual version I have.  Thanks.
Also
Please can you tell me the command to make the downloaded file executable?
Thanks for your efforts 
73’s de Enzo IK8OZV

**Comment by dl1ksv** [comment]
To make a file executable use a terminal window:
cd "directoryname"
The directoryname is the name of the directory that contains the file.

Then 
chmod + x filename

Now you can execute the file by

./filename

To test the downloaded file you don't have to uninstall  anything.

No idea why you get the QSocketNotifier message.
The output itself looks good. The dongle is initialized and it is set to 144800 kHz.  Up to here there seems to be no error.
The next step would be to start the device from the gui.
 I get the libusb warnings when I run the appimage , too, but the dongle works.

**Comment by ik8ozv** [comment]
@dl1ksv 

when i give 

./Gqrx-2.16-x86_64.AppImage

After done the comans:

chmod +x Gqrx-2.16-x86_64.AppImage

i get:

./Gqrx-2.16-x86_64.AppImage
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

Thanks

**Comment by dl1ksv** [comment]
You have three options:

1.  Follow the recommendations given in the link above
2. Run ./Gqrx-2.16-x86_64.AppImage --appimage-extract which builds a new directory. Switch to that directory and run ./AppRun
3. Report a bug to Ubuntu

**Comment by ik8ozv** [comment]
@dl1ksv 
When i go to open the program i get always the warning:

Failed to set input device
audio_alsa_source
Please select another device.

In this version i can see just one Funcube called:

FUNCube Dongle V2.0

Please what to do?
maybe the driver is not installed correctly.
Any way to check if installed correctly?
Thanks

73's de Enzo IK8OZV

**Comment by dl1ksv** [comment]
Seeing only FUNCube Dongle V2.0 is OK. You can try to run grc and there one of the examples using gr-funcube.

**Comment by ik8ozv** [comment]
I have tried the fmfcdpp one but i hear the audio with a lot of vibrations.
Any hint please?
Thanks

**Comment by dl1ksv** [comment]
So the driver is availabe and working.

**Comment by ik8ozv** [comment]
Please any help?
I am still struggling.
When i run it from terminal with the command:

/usr/local/bin/gqrx

the gqrx doess not load up and in the terminal i read:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.1.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
file_source :warning: file size is not a multiple of item size
rx_nb_cc :info: set_min_output_buffer on block 12 to 32768
Resampling audio 96000 -> 48000
BandPlanFile is /home/enzo/.config/gqrx/bandplan.csv
BookmarksFile is /home/enzo/.config/gqrx/bookmarks.csv
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
libusb: warning [libusb_exit] device 4.1 still referenced
libusb: warning [libusb_exit] device 3.4 still referenced
libusb: warning [libusb_exit] device 3.3 still referenced
libusb: warning [libusb_exit] device 3.5 still referenced
libusb: warning [libusb_exit] device 3.2 still referenced
libusb: warning [libusb_exit] device 3.1 still referenced
libusb: warning [libusb_exit] device 2.1 still referenced
libusb: warning [libusb_exit] device 1.1 still referenced
QFSFileEngine::open: No file name specified
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.1.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
Using FUNcube Dongle V2.0 (hw:1)
Segmentation fault (core dumped)

Please any help?
Thanks
73's de Enzo IK8OZV
