### ISSUE TITLE
More detailed installation instructions needed

### ISSUE THREAD

**Issue by duggabe** [dl1ksv/gr-funcube#12]
Although the basic instructions for installing an OOT are all about the same, more details are needed for those with less experience. Here are what I believe to be the complete installation instructions for gr-funcube:

```
cd $HOME
sudo apt install libusb-1.0-0-dev libudev-dev libhidapi-dev python3-pip
sudo pip install --upgrade setuptools
gnuradio-config-info --prefix
git clone https://github.com/dl1ksv/gr-funcube.git
cd $HOME/gr-funcube
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=<prefix from gnuradio-config-info> ../
make
sudo make install
sudo ldconfig
cd /etc/udev/rules.d
sudo cp ~/gr-funcube/50-funcube.rules ./
sudo udevadm control --reload-rules
sudo udevadm trigger
```

**Comment by duggabe** [comment]
Minor correction to above, the line "sudo pip install --upgrade setuptools" should not have "sudo" in it and should be:
"pip install --upgrade setuptools"

These instructions have been tested with Ubuntu 22.04.2 and GNU Radio 3.10.6.0

**Comment by dl1ksv** [comment]
@duggabe Many thanks for your improvements.  
Just some remarks.
I'm working with Fedora.  The package names are sligtly different and  you'll find the udev rules in 
/usr/lib/udev/rules.d/

So we had to differ between different distros.
I'm not sure if udevadm is required.  Does systemd-udevd updates it's database if it detects a new rules file?

Why do you use pip to install setuptools? Is there no setuptool package on Ubuntu.

**Comment by duggabe** [comment]
I raised this issue due to several questions on the GNU Radio chat room https://app.element.io/#/room/#gnuradio:gnuradio.org

The instructions could be introduced with a caveat about being for Ubuntu.

As I understand it, udevd does not update when a new rule is added, so the reload rules and the trigger are needed unless one reboots the computer.

When I was searching for the correct name for 'libhidapi-dev', I came across the setuptools. It was unclear if it was needed or not, so I added it. If not needed, don't include it ;)

I appreciate your continued support for FunCube.

**Comment by dl1ksv** [comment]
@duggabe I setup a new branch improve_inst, where I addedyour installation instructions as examble for Ubuntu.
Could you please have a look at it? Improvements are welcome.

Thanks
-- Volker

**Comment by duggabe** [comment]
Looks good!
Two minor corrections:
change "sudo cp ~/gr-funcube/50-funcube.rules ./" to "sudo cp $HOME/gr-funcube/50-funcube.rules ./"
and in the last line of Credits, put the 'a' in 'example' :)

**Comment by dl1ksv** [comment]
Thanks again, just merged.
