### ISSUE TITLE
Strange library soname: libgnuradio-funcube.so.v1.0-compat-xxx-xunknown

### ISSUE THREAD

**Issue by yarda** [dl1ksv/gr-funcube#2]
I was building from the tag v3.9.0 and it built library with strange name:
libgnuradio-funcube.so.v1.0-compat-xxx-xunknown

**Comment by yarda** [comment]
```
libgnuradio-funcube.so -> libgnuradio-funcube.so.1.0.0git
libgnuradio-funcube.so.v1.0-compat-xxx-xunknown
libgnuradio-funcube.so.1.0.0git -> libgnuradio-funcube.so.v1.0-compat-xxx-xunknown
```

**Comment by dl1ksv** [comment]
Did you build from the downloaded zip file?
I'll have a look.

**Comment by yarda** [comment]
I built it from the tag, i.e.:
https://github.com/dl1ksv/gr-funcube/archive/v3.9.0/gr-funcube-3.9.0.tar.gz

**Comment by dl1ksv** [comment]
Fixed
